---
title: "Case_study1"
author: "Bthyw"
date: "9/2/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(janitor)
library(dplyr)
library(lubridate)
library(ggplot2)
Divvy_Trips_2019_Q3 <- read.csv("C:/Users/Nonnon/Downloads/BP/Google Analytics/Rstudio/Divvy_Trips/Divvy_Trips_2019_Q3.csv")
Divvy_Trips_2019_Q4 <- read.csv("C:/Users/Nonnon/Downloads/BP/Google Analytics/Rstudio/Divvy_Trips/Divvy_Trips_2019_Q4.csv")
Divvy_Trips_2020_Q1 <- read.csv("C:/Users/Nonnon/Downloads/BP/Google Analytics/Rstudio/Divvy_Trips/Divvy_Trips_2020_Q1.csv")
```

### Combine into a single data.frame
```{r}
Divvy_Trips_2020_Q1<-Divvy_Trips_2020_Q1 %>% 
  rename(trip_id= ride_id,bikeid= rideable_type,start_time= started_at,end_time= ended_at,from_station_id= start_station_id,from_station_name= start_station_name,to_station_id=end_station_id,to_station_name= end_station_name, usertype=member_casual)
Divvy_Trips_2020_Q1<-Divvy_Trips_2020_Q1 %>% 
  select(-c(start_lat,start_lng,end_lat,end_lng))

Divvy_Trips_2019<- rbind(Divvy_Trips_2019_Q3,Divvy_Trips_2019_Q4)
Divvy_Trips_2019<-Divvy_Trips_2019 %>% 
  select(-c(gender,birthyear,tripduration))
all_trips<-rbind(Divvy_Trips_2019,Divvy_Trips_2020_Q1)
```

```{r}
all_trips$from_station_id<-as.character(all_trips$from_station_id)
all_trips$to_station_id<-as.character(all_trips$to_station_id)

all_trips$usertype<-all_trips$usertype %>% 
  recode("casual"="Customer","member"="Subscriber")
```

### Time interval
```{r}
all_trips$date<-as.Date(all_trips$start_time)
all_trips$day<-format(as.Date(all_trips$date),"%d")
all_trips$month<-format(as.Date(all_trips$date),"%m")
all_trips$year<-format(as.Date(all_trips$date),"%Y")

all_trips$day_of_week<-format(as.Date(all_trips$date),"%A")

all_trips$ride_length<-difftime(all_trips$end_time,all_trips$start_time)
all_trips$ride_length<-as.numeric(as.character(all_trips$ride_length))
```

### Oversee data trends by using table
```{r}
all_trips$day_of_week<-ordered(all_trips$day_of_week,levels=c("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"))
#all_trips$year<-ordered(all_trips$year,levels=c("2019","2020"))
aggregate(all_trips$ride_length~all_trips$usertype+all_trips$day_of_week,FUN = mean)
```

### Analyze ridership data by type and weekday
```{r}
all_trips<-all_trips %>% 
  mutate(weekday=wday(start_time,label = TRUE)) %>% 
  group_by(weekday,usertype) %>% #then cal the number of rides&average time duration
  summarise(number_ride=n(),average_duration=mean(ride_length)) %>% 
  arrange(usertype,weekday)
```

### Visualize the number of rides by rider type
```{r}
ggplot(data = all_trips,mapping = aes(x=weekday,y=number_ride,fill=usertype))+
  geom_col(position = "dodge")
```
### Visualize the average duration
```{r}
ggplot(data = all_trips,mapping = aes(x=weekday,y=average_duration,fill=usertype))+
  geom_col(position = "dodge")
```

